# SPDX-License-Identifier: Apache-2.0
# BMV2_SWITCH_EXE = simple_switch_grpc
# TOPO = triangle-topo/topology.json

# include ../../utils/Makefile

# SPDX-License-Identifier: Apache-2.0
BMV2_SWITCH_EXE = simple_switch_grpc
TOPO = hw3-1,3-2/2h4w.json

include ../../utils/Makefile